### ISSUE TITLE
앱 종료 시에도 뷰 상태 저장

### ISSUE THREAD

**Issue by yuseon-Lim** [HSUITContestTeam/map-app#126]
- firebase에 저장하거나(로그인 하면 맵 유지됨), 뷰 상태를 유지하는 방식(앱 삭제하면 사라짐).. 으로 구현

**Comment by im-shung** [comment]
서버에 저장해야 하는 것들 
1. binding.icMapOfSouthKorea.findRichPathByName("$mapName")!!.originalWidth.toInt()
> 각 path width, height 크기 -> 이미지뷰 크기에 적용
> > 굳이 서버에 저장안하고,,음 미리 설정해놓아도 될듯 
2. 지도 pathData
