### ISSUE TITLE
갤러리 사진 불러오는 기능 구현

### ISSUE THREAD

**Issue by yuseon-Lim** [HSUITContestTeam/map-app#26]
![image](https://user-images.githubusercontent.com/67352902/125885299-52f0cdfc-6182-4ac9-8ed8-4c57d442defb.png)

- 이런 느낌
- 사진 GPS 정보 이용할 수 있는지도 조사

**Comment by im-shung** [comment]
#39 갤러리 사진 작업

**Comment by im-shung** [comment]
#40 권한 추가

**Comment by yuseon-Lim** [comment]
서영 근데 이거 어디에있오..?

**Comment by im-shung** [comment]
![image](https://user-images.githubusercontent.com/67851738/126649575-1fef105b-11e8-400b-84d2-2996ab339358.png)
대충 저 노란색 부위 누르면 나와!
