### ISSUE TITLE
지도화면 이미지뷰, 버튼, drawble 등 ,, 실험/시도

### ISSUE THREAD

**Issue by yuseon-Lim** [HSUITContestTeam/map-app#48]
- 해본것 공유해주면 감사 :)

**Comment by im-shung** [comment]
https://user-images.githubusercontent.com/67851738/126867885-6877807c-5857-46eb-beed-a9fdc070405a.mp4
<img width="220" alt="겹쳐져 있는 상태" src="https://user-images.githubusercontent.com/67851738/126867898-02c3be32-6852-450c-bfc4-4f3525e83119.png">

구글링으로 성공했어영~!~!~!~ 좀만 쉬고 정리해서 올릴게영
