### ISSUE TITLE
firebase 연동

### ISSUE THREAD

**Issue by yuseon-Lim** [HSUITContestTeam/map-app#62]
- 계정이나 필요한 정보(토큰?값? 등등) 슬랙에 공유

**Comment by im-shung** [comment]
![image](https://user-images.githubusercontent.com/67851738/127081307-a9c6456e-6ded-4eb8-97d5-8081a7480488.png)

안드로이드 스튜디오 상단 탭 Tools > Firebase 
여기에 회원가입, 저장소 등등 예제들이 있는 것 같음~
