### ISSUE TITLE
강원도 지도 프래그먼트 이미지뷰 클릭 이벤트 구현

### ISSUE THREAD

**Issue by yuseon-Lim** [HSUITContestTeam/map-app#78]
- 갤러리 불러오기 구현..

@im-shung 근데 우리 이미지뷰 클릭하면 바로 갤러리가 아니라 화면 하나 더 떠야하지 않아?
사진설정하거나 변경, 색 지정 이런거

**Comment by yuseon-Lim** [comment]
![image](https://user-images.githubusercontent.com/67352902/127775239-98aeaa09-a66e-49ff-b678-6ace421c29fa.png)

이런식?

**Comment by im-shung** [comment]
![image](https://user-images.githubusercontent.com/67851738/128373949-4979b5f6-1965-4fcf-9d5a-42fa119ac3c2.png)

> 사진은 강원도 프래그먼트 

기본 지도 화면과 Map 1은 강원도프래그먼트화면으로 구성돼있음

일단은 인제랑 고성부분만 클릭이벤트를 만들었음 

국내지도 이미지 인제,고성 부분 위치와 강원도 프래그먼트의 인제,고성 부분 위치가 완전히 일치하지는 않기 때문에 
아직은 인제,고성의 경계선 밖이 클릭될 수 있음

인제를 클릭했을 때 하단의 Run 탭에 "Inje click", 고성을 클릭했을 때는 "Goseong click" 이 출력될 것임
